### ISSUE TITLE
missing ) after argument list

### ISSUE THREAD

**Issue by thenglong** [imjuni/erdia#12]
I ran this command 
`ts-node -r tsconfig-paths/register ./node_modules/.bin/erdia er -d ...`
And it gave me an error like this.

My env
* windows 11
* node 16.17.0
* npm 8.15.0
* typescript 4.7.2

![image](https://user-images.githubusercontent.com/49927604/188251436-02dbde2f-8be2-4597-b84d-48ab4a9ebdd3.png)

**Comment by imjuni** [comment]
Hi @thenglong 

If you installed in a Window 11, npm create shell command instead of symbolic link.

Change command below,

`ts-node -r tsconfig-paths/register ./node_modules/erdia/dist/cli.js er -d ...`

Thank you 👍
