### ISSUE TITLE
Index Exception on running the build command

### ISSUE THREAD

**Issue by atif** [imjuni/erdia#56]
I'm getting an error while running the `npx erdia build` command.
<img width="1728" alt="Screenshot 2024-01-18 at 3 38 49 PM" src="https://github.com/imjuni/erdia/assets/201002/f3273fbf-b2b6-4570-b3ed-b58296529103">

I've setup `"data-source-path": "dist/database/data-source.js"` in .erdiarc.

I'm not sure why it's referring to src/ts files in the error log instead of dist/js files. Kindly guide me how to fix it

**Comment by imjuni** [comment]
The `index exception` error frequently appears when the entity model cannot find the inverse entity in a relation. Could you please create a repo to reproduce this issue?
