### ISSUE TITLE
Failing on ManyToMany

### ISSUE THREAD

**Issue by AlexChuv** [imjuni/erdia#77]
Getting error `Cannot found relation: {parent_entity} - undefined` in this line: `erdia/src/typeorm/relations/dedupeManaToManyRelationRecord.ts:27:7
`

Defining the relationship like:

 ```
@JoinTable({ name: 'parent_entity_child_entity' })
@ManyToMany(() => ChildEntity)
child: ChildEntity[]
```

**Comment by imjuni** [comment]
@AlexChuv @d3bug-git  

Hello,  

Thank you for patiently waiting. I recently started a new job, so I haven’t had enough time to work on this project. However, I’ve released a new version with the PR applied, which addresses the issue.  

@d3bug-git Thank you for your valuable contribution!
